version: "3.8"
services:
  strapi:
    image: strapi/strapi
    ports:
      - "1337:1337"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -nv -t1 --spider 'http://localhost:1337' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=postgres
      - DATABASE_HOST=strapi-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=c9ee5e90442e0e2528552a81f7900621
    volumes:
      - strapi_data:/srv/app
    networks:
      - backend
      - frontend
  strapi-db:
    image: postgres
    healthcheck:
      test: ["CMD", "postgres-healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback

    configs:
      - source: postgres-healthcheck
        target: /usr/local/bin/postgres-healthcheck
        mode: 0555
    environment:
      - POSTGRES_PASSWORD=c9ee5e90442e0e2528552a81f7900621
      - POSTGRES_DB=postgres
      - POSTGRES_USER=strapi
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - strapi_pg_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  strapi_pg_data:
  strapi_data:

configs:
  postgres-healthcheck:
    file: ./postgres-healthcheck
